### ISSUE TITLE
The fix in 3.0.0.rc8 does not work in test env

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/i18n-js#1]
```
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/sprockets-2.10.1/lib/sprockets/index.rb:81:in `expire_index!': can't modify immutable index (TypeError)
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/sprockets-2.10.1/lib/sprockets/base.rb:175:in `register_preprocessor'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/i18n-js-pika-3.0.0.rc8/lib/i18n/js/engine.rb:11:in `block (2 levels) in <class:Engine>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:36:in `call'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:180:in `each'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /Users/PikachuEXE/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
    from /Users/PikachuEXE/Projects/spacious-rails/config/environment.rb:5:in `<top (required)>'
    from /Users/PikachuEXE/Projects/spacious-rails/spec/spec_helper.rb:11:in `require'
    from /Users/PikachuEXE/Projects/spacious-rails/spec/spec_helper.rb:11:in `block in <top (required)>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/spork-1.0.0rc4/lib/spork.rb:24:in `prefork'
    from /Users/PikachuEXE/Projects/spacious-rails/spec/spec_helper.rb:6:in `<top (required)>'
    from /Users/PikachuEXE/Projects/spacious-rails/spec/cells/authentication_box_cell_spec.rb:1:in `require'
    from /Users/PikachuEXE/Projects/spacious-rails/spec/cells/authentication_box_cell_spec.rb:1:in `<top (required)>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by ideadapt** [comment]
Any hints on how to fix this?

**Comment by PikachuEXE** [comment]
Oh i have updated to `3.0.0.rc9` (2 months ago)
Please update and try first :)
